apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yio4bkq3v-go 
  janus-idp.io/tekton: yio4bkq3v-go
  backstage.io/kubernetes-id: yio4bkq3v-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yio4bkq3v-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  